### ISSUE TITLE
MoveTowardsが効かない！！

### ISSUE THREAD

**Issue by julien120** [julien120/Unity_InakiriGames#1]
### 理想：
魚がwayColiderタグに当たるとwaypointに向けてMoveTowardsするようにしたい
### 問題：
最初は上手く動いたが、"何もしてないのに”MoveTowardsできなくなった。NavMeshできないのでどうにか解決したい。

### 問題のコード

public GameObject[] waypoint = new GameObject[4]; 
int count = 0;

 private void OnTriggerEnter2D(Collider2D coll)
    {
        Debug.Log("判定");
        if (coll.gameObject.CompareTag("waypointCollider"))
        {
           Debug.Log("wayポイント更新" + count);
            transform.position = Vector2.MoveTowards(transform.position, waypoint[count].transform.position, 10 * Time.deltaTime);
            count++;
            Debug.Log("wayポイント更新" + count);
        }
    }

**Comment by Shunya078** [comment]
## 解決結論
OnTriggerEnter2Dは衝突した１度しか呼ばれないので、
このメソッド内で実行する内容はwaypointの更新のみ書いてあげるのがベストです。

MoveTowardsは目的地に向かって毎フレーム進んでいくことが想定されているので、
移動自体はUpdate(本当はFixedUpdateの方がベストです、移動処理は処理的に同区間フレームで動くべきなので)に
書いてあげると解決できるかと思います！

```
void Update()
    {
        transform.position = Vector2.MoveTowards(transform.position, waypoint[count].transform.position, 10 * Time.deltaTime);

    }

  
    private void OnTriggerEnter2D(Collider2D coll)
    {
        Debug.Log("判定");
        if (coll.gameObject.CompareTag("waypointCollider"))
        {
            Debug.Log("wayポイント更新" + count);
            Debug.Log(waypoint[count].transform.position);

            //transform.position = Vector2.MoveTowards(transform.position, waypoint[count].transform.position, 10 * Time.deltaTime);
         
            // count++;
            //Debug.Log("wayポイント更新" + count);
        }
    }
```
### 参考資料(ログ用)
- MoveTowardsリファレンスより参照
[https://docs.unity3d.com/ja/current/ScriptReference/Vector2.MoveTowards.html](url)
- Unity メソッドのライフサイクルにFixedUpdateとUpdateの違い
[https://docs.unity3d.com/ja/2018.4/Manual/ExecutionOrder.html](url)

## 解決のために行った手順

1. 衝突にてOnTriggerがちゃんと取れているか
 *- Debug.Log()とCollderのisTriggerをそれぞれ確認、Debug.Log("判定")が出たので検知されている
2. waypointが配列のデータ内にドラッグ&ドロップできているか
3. Debug.Log(waypoint[count].transform.position)にて目的地の座標が取れているか確認
4. 移動方法がMoveTowardsなので、Updateじゃないと動かないことに気づく
 *- Debug.Log("判定")が1回しか呼ばれてないのをみて気づいた
